server:
  port: 4014
spring:
  main:
    banner-mode: 'off'
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/practice
    username: postgres
    password: radiant
logging:
  level:
    org.springframework: DEBUG
    com.rs.app: DEBUG