CREATE TABLE IF NOT EXISTS JDBC_USER(ID SERIAL, NAME VARCHAR, EMAIL VARCHAR);

CREATE TABLE IF NOT EXISTS JDBC_BOOK(ID SERIAL PRIMARY KEY, TITLE VARCHAR, AUTHOR VARCHAR, PRICE NUMERIC (3, 2), PUBLISHER VARCHAR);